Repository Freelancer-Sirius-Revival/FLSR, pull requests merged in 2023-06, with the labels that each got.

#643 Deleting "whatever.mat"
  DATA/FX/SHIELDS/shields_ale.ini
Labels: bug

#647 Deleting unused Gold and Niob mineable asteroid field
  DATA/SOLAR/ASTEROIDS/br04_niob_mine.ini
  DATA/SOLAR/ASTEROIDS/br05_gold_mine.ini
Labels: change

#645 Adjusting LOD Ranges for gas Effects and Asteroid Solar
  DATA/FX/effects.ini
  DATA/SOLAR/solararch.ini
Labels: change

#644 Deleting old and outdated dynamic mineable field
  DATA/UNIVERSE/SYSTEMS/BR04/br04.ini
Labels: bug

#654 Correct interior doors on Space_port_dmg Add new models Space_port01 …
  DATA/SOLAR/DOCKABLE/space_port01.cmp
  DATA/SOLAR/DOCKABLE/space_port01.sur
  DATA/SOLAR/DOCKABLE/space_port_dmg.cmp
  DATA/SOLAR/DOCKABLE/space_port_dmg.sur
  DATA/SOLAR/DOCKABLE/space_port_dock.cmp
  DATA/SOLAR/DOCKABLE/space_port_dock.sur
  DATA/SOLAR/loadouts.ini
  DATA/SOLAR/solararch.ini
Labels: enhancement
