Repository Freelancer-Sirius-Revival/FLSR, pull requests merged in 2023-04, with the labels that each got.

#552 Adjusting sell price for silver on new tokyo
  DATA/EQUIPMENT/market_commodities.ini
Labels: bug

#551 Adjusting Drop values for Mineable Zones
  DATA/SOLAR/ASTEROIDS/bw03_fursten_gas_pocket.ini
  DATA/SOLAR/ASTEROIDS/bw03_img_mineable.ini
Labels: change

#519 489 convert tradelanes in tau 31
  DATA/SOLAR/ASTEROIDS/bw10_ice_crystal_field.ini
  DATA/UNIVERSE/SYSTEMS/Bw10/Bw10.ini
Labels: change

#574 Corrected Falken shield type
  DATA/EQUIPMENT/shield_equip.ini
Labels: bug

#573 Applied changes to Omega 3
  DATA/UNIVERSE/SYSTEMS/Bw01/Bw01.ini
Labels: change

#582 Kusari Drake Update Reworked SUR and Wireframes
  DATA/SHIPS/KUSARI/KU_FIGHTER/ku_fighter.cmp
  DATA/SHIPS/KUSARI/KU_FIGHTER/ku_fighter.sur
  DATA/SHIPS/KUSARI/KU_FIGHTER/ku_fighter_dmg_engine01.3db
  DATA/SHIPS/KUSARI/KU_FIGHTER/ku_fighter_dmg_engine01.sur
  DATA/SHIPS/KUSARI/KU_FIGHTER/ku_fighter_dmg_wing_port.3db
  DATA/SHIPS/KUSARI/KU_FIGHTER/ku_fighter_dmg_wing_port.sur
  DATA/SHIPS/KUSARI/KU_FIGHTER/ku_fighter_dmg_wing_starboard.3db
  DATA/SHIPS/KUSARI/KU_FIGHTER/ku_fighter_dmg_wing_starboard.sur
  DATA/SHIPS/KUSARI/KU_FIGHTER/ku_fighter_shield.3db
  DATA/SHIPS/KUSARI/KU_FIGHTER/ku_fighter_shield.sur
Labels: enhancement
