Repository Freelancer-Sirius-Revival/FLSR, pull requests merged in 2024-10, with the labels that each got.

#934 Updates for space mining & factory models
  DATA/SOLAR/DOCKABLE/space_factory01.cmp
  DATA/SOLAR/DOCKABLE/space_factory01.sur
  DATA/SOLAR/DOCKABLE/space_factory02.cmp
  DATA/SOLAR/DOCKABLE/space_factory02.sur
  DATA/SOLAR/DOCKABLE/space_mining01.cmp
  DATA/SOLAR/DOCKABLE/space_mining01.sur
Labels: enhancement

#932 Rheinland humpback freighter model updated revision01
  DATA/SHIPS/RHEINLAND/RH_FREIGHTER/rh_freighter.cmp
  DATA/SHIPS/RHEINLAND/RH_FREIGHTER/rh_freighter.sur
Labels: enhancement

#939 Adding surprise container
  DATA/EQUIPMENT/MODELS/ICONS/GOODS/Icon_Surprise_Blueprint_EQ.3db
  DATA/EQUIPMENT/MODELS/ICONS/GOODS/Icon_Surprise_Blueprint_SHP.3db
  DATA/EQUIPMENT/MODELS/ICONS/GOODS/Icon_Surprise_Blueprint_WP.3db
  DATA/EQUIPMENT/MODELS/ICONS/GOODS/Icon_Surprise_Bronze.3db
  DATA/EQUIPMENT/MODELS/ICONS/GOODS/Icon_Surprise_Christmas.3db
  DATA/EQUIPMENT/MODELS/ICONS/GOODS/Icon_Surprise_FLSR.3db
  DATA/EQUIPMENT/MODELS/ICONS/GOODS/Icon_Surprise_Gold.3db
  DATA/EQUIPMENT/MODELS/ICONS/GOODS/Icon_Surprise_Halloween.3db
  DATA/EQUIPMENT/MODELS/ICONS/GOODS/Icon_Surprise_Silver.3db
  DATA/EQUIPMENT/commodity_equip.ini
  DATA/EQUIPMENT/commodity_good.ini
  DATA/MISSIONS/lootprops.ini
  DATA/SHIPS/loadouts.ini
  DATA/SHIPS/loadouts_br.ini
  DATA/SHIPS/loadouts_co.ini
  DATA/SHIPS/loadouts_ku.ini
  DATA/SHIPS/loadouts_li.ini
  DATA/SHIPS/loadouts_rh.ini
  EXE/flhook_plugins/FLSR-LootBoxes.cfg
Labels: enhancement

#941 Enhancing glacial beasts loadouts
  DATA/EQUIPMENT/engine_equip.ini
  DATA/EQUIPMENT/engine_good.ini
  DATA/EQUIPMENT/weapon_equip.ini
  DATA/EQUIPMENT/weapon_good.ini
  DATA/FX/ENGINES/engines_ale.ini
  DATA/FX/ENGINES/gf_gb_smallengine02_fire.ale
  DATA/FX/ENGINES/gf_gb_smallengine02_trail.ale
  DATA/FX/WEAPONS/fc_gb_plasma_01.ale
  DATA/FX/WEAPONS/fc_gb_plasma_02.ale
  DATA/FX/WEAPONS/weapons_ale.ini
  DATA/FX/beam_effects.ini
  DATA/FX/effects.ini
  DATA/MISSIONS/faction_prop.ini
  DATA/MISSIONS/lootprops.ini
  DATA/MISSIONS/npcships.ini
  DATA/SHIPS/loadouts.ini
Labels: enhancement

#940 Adding grims halloween set
  DATA/AUDIO/SOUNDS/WEAPONS/fire_tachyon_06_xsx.wav
  DATA/AUDIO/SOUNDS/WEAPONS/fire_tachyon_07_xsx.wav
  DATA/AUDIO/sounds.ini
  DATA/EQUIPMENT/engine_equip.ini
  DATA/EQUIPMENT/engine_good.ini
  DATA/EQUIPMENT/weapon_equip.ini
  DATA/EQUIPMENT/weapon_good.ini
  DATA/FX/ENGINES/engines_ale.ini
  DATA/FX/ENGINES/halloween_smallengine01_fire.ale
  DATA/FX/ENGINES/halloween_smallengine01_trail.ale
  DATA/FX/ENGINES/halloween_smallengine02_fire.ale
  DATA/FX/ENGINES/halloween_smallengine02_trail.ale
  DATA/FX/WEAPONS/Halloween_tachyon_01.ale
  DATA/FX/WEAPONS/Halloween_tachyon_02.ale
  DATA/FX/WEAPONS/weapons_ale.ini
  DATA/FX/effects.ini
  DATA/MISSIONS/lootprops.ini
Labels: enhancement

#933 Borderworld dromedary updated to revision01
  DATA/SHIPS/BORDER_WORLD/BW_FREIGHTER/bw_eng_dmg.3db
  DATA/SHIPS/BORDER_WORLD/BW_FREIGHTER/bw_eng_dmg.sur
  DATA/SHIPS/BORDER_WORLD/BW_FREIGHTER/bw_freighter.cmp
  DATA/SHIPS/BORDER_WORLD/BW_FREIGHTER/bw_freighter.sur
  DATA/SHIPS/loadouts.ini
  DATA/SHIPS/shiparch.ini
Labels: enhancement

#953 Fixing Typo in Wreck Loadout
  DATA/UNIVERSE/SYSTEMS/HI01/hi01.ini
Labels: bug

#954 Halloween event
  DATA/AUDIO/MUSIC/music_li_danger02.wav
  DATA/AUDIO/SOUNDS/FX/dk_Shieldhit.wav
  DATA/AUDIO/music.ini
  DATA/AUDIO/sounds.ini
  DATA/EQUIPMENT/MODELS/COMMODITIES/CRATES/ast_loot_pumpkin.3db
  DATA/EQUIPMENT/MODELS/COMMODITIES/CRATES/ast_loot_pumpkin.sur
  DATA/EQUIPMENT/MODELS/COMMODITIES/CRATES/pod_pumpkin.3db
  DATA/EQUIPMENT/MODELS/COMMODITIES/CRATES/pod_pumpkin.sur
  DATA/EQUIPMENT/MODELS/ICONS/GOODS/Icon_halloween_pumpkin.3db
  DATA/EQUIPMENT/commodity_equip.ini
  DATA/EQUIPMENT/commodity_good.ini
  DATA/EQUIPMENT/shield_equip.ini
  DATA/EQUIPMENT/shield_good.ini
  DATA/FX/effects.ini
  DATA/MISSIONS/ENCOUNTERS/area_boss.ini
  DATA/MISSIONS/faction_prop.ini
  DATA/MISSIONS/lootprops.ini
  DATA/MISSIONS/npcships.ini
  DATA/SHIPS/loadouts.ini
  DATA/SHIPS/loadouts_special.ini
  DATA/SHIPS/shiparch.ini
  DATA/UNIVERSE/SYSTEMS/IW05/iw05.ini
  DATA/UNIVERSE/SYSTEMS/IW06/iw06.ini
  DATA/UNIVERSE/SYSTEMS/LI01/li01.ini
  DATA/UNIVERSE/SYSTEMS/LI05/li05.ini
  DATA/initialworld.ini
  EXE/flhook_plugins/FLSR-Crafting.cfg
  EXE/flhook_plugins/FLSR-LootBoxes.cfg
Labels: enhancement, change

#946 Upgrade bounty hunter ships
  DATA/SHIPS/BOUNTY_HUNTER/BH_ELITE/bh_elite.cmp
  DATA/SHIPS/BOUNTY_HUNTER/BH_ELITE/bh_elite.sur
  DATA/SHIPS/BOUNTY_HUNTER/BH_FIGHTER/bh_dmg_port_wing.3db
  DATA/SHIPS/BOUNTY_HUNTER/BH_FIGHTER/bh_dmg_port_wing.sur
  DATA/SHIPS/BOUNTY_HUNTER/BH_FIGHTER/bh_dmg_star_wing.3db
  DATA/SHIPS/BOUNTY_HUNTER/BH_FIGHTER/bh_dmg_star_wing.sur
  DATA/SHIPS/BOUNTY_HUNTER/BH_FIGHTER/bh_dmg_topfin.3db
  DATA/SHIPS/BOUNTY_HUNTER/BH_FIGHTER/bh_dmg_topfin.sur
  DATA/SHIPS/BOUNTY_HUNTER/BH_FIGHTER/bh_fighter.cmp
  DATA/SHIPS/BOUNTY_HUNTER/BH_FIGHTER/bh_fighter.sur
  DATA/SHIPS/BOUNTY_HUNTER/BH_FIGHTER2/bh_fighter2.cmp
  DATA/SHIPS/BOUNTY_HUNTER/BH_FIGHTER2/bh_fighter2.sur
  DATA/SHIPS/BOUNTY_HUNTER/BH_FIGHTER3/bh_fighter3.cmp
  DATA/SHIPS/BOUNTY_HUNTER/BH_FIGHTER3/bh_fighter3.sur
  DATA/SHIPS/BOUNTY_HUNTER/BH_FIGHTER4/bh_fighter4.cmp
  DATA/SHIPS/BOUNTY_HUNTER/BH_FIGHTER4/bh_fighter4.sur
  DATA/SHIPS/BOUNTY_HUNTER/BH_SHEAVY_FIGHTER/bh_sheavy_fighter.cmp
  DATA/SHIPS/BOUNTY_HUNTER/BH_SHEAVY_FIGHTER/bh_sheavy_fighter.sur
  DATA/SHIPS/BOUNTY_HUNTER/BH_UHEAVY_FIGHTER/bh_uheavy_fighter.cmp
  DATA/SHIPS/BOUNTY_HUNTER/BH_UHEAVY_FIGHTER/bh_uheavy_fighter.sur
  DATA/SHIPS/BOUNTY_HUNTER/BH_VHEAVY_FIGHTER/bh_vheavy_fighter.cmp
  DATA/SHIPS/BOUNTY_HUNTER/BH_VHEAVY_FIGHTER/bh_vheavy_fighter.sur
Labels: enhancement

#966 Adjusting Halloween Drop Rates (More Pumpkins than Blueprints)
  EXE/flhook_plugins/FLSR-LootBoxes.cfg
Labels: change
