Repository Freelancer-Sirius-Revival/FLSR, pull requests merged in 2024-09, with the labels that each got.

#892 Nomad weapon textures, showing in spectator/observer ship
  DATA/SHIPS/shiparch.ini
Labels: bug

#897 New l codenames
  DATA/AUDIO/SOUNDS/WEAPONS/fire_laser7_xsx.wav
  DATA/AUDIO/SOUNDS/WEAPONS/fire_photon6_xsx.wav
  DATA/AUDIO/sounds.ini
  DATA/EQUIPMENT/commodity_equip.ini
  DATA/EQUIPMENT/commodity_good.ini
  DATA/EQUIPMENT/weapon_equip.ini
  DATA/EQUIPMENT/weapon_good.ini
  DATA/FX/beam_effects.ini
  DATA/FX/effects.ini
  DATA/SOLAR/loadouts_wrecks.ini
  EXE/flhook_plugins/FLSR-Crafting.cfg
Labels: enhancement

#898 New transport engines 01
  DATA/EQUIPMENT/commodity_equip.ini
  DATA/EQUIPMENT/commodity_good.ini
  DATA/EQUIPMENT/engine_equip.ini
  DATA/EQUIPMENT/engine_good.ini
  DATA/EQUIPMENT/market_commodities.ini
  DATA/EQUIPMENT/market_misc.ini
  DATA/FX/ENGINES/engines_ale.ini
  DATA/FX/ENGINES/gf_br_transport_engine02_fire.ale
  DATA/FX/ENGINES/gf_br_transport_engine02_trail.ale
  DATA/FX/ENGINES/gf_co_transport_engine01_fire.ale
  DATA/FX/ENGINES/gf_co_transport_engine01_trail.ale
  DATA/FX/ENGINES/gf_corsair_transport_engine01_fire.ale
  DATA/FX/ENGINES/gf_corsair_transport_engine01_trail.ale
  DATA/FX/ENGINES/gf_ku_transport_engine01_fire.ale
  DATA/FX/ENGINES/gf_ku_transport_engine01_trail.ale
  DATA/FX/ENGINES/gf_li_transport_engine01_fire.ale
  DATA/FX/ENGINES/gf_li_transport_engine01_trail.ale
  DATA/FX/ENGINES/gf_ou_transport_engine01_fire.ale
  DATA/FX/ENGINES/gf_ou_transport_engine01_trail.ale
  DATA/FX/ENGINES/gf_rh_transport_engine01_fire.ale
  DATA/FX/ENGINES/gf_rh_transport_engine01_trail.ale
  DATA/FX/effects.ini
  EXE/flhook_plugins/FLSR-Crafting.cfg
Labels: enhancement

#915 Increasing Range +100m
  DATA/EQUIPMENT/weapon_equip.ini
Labels: change
